# Generated by Django 2.0 on 2019-09-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.SmallIntegerField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=7)),
                ('birthday', models.DateTimeField()),
            ],
        ),
    ]
