# Generated by Django 2.0 on 2019-09-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='news1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=7)),
                ('age', models.SmallIntegerField()),
                ('headpic', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='User1',
        ),
        migrations.DeleteModel(
            name='news',
        ),
    ]
